### ISSUE TITLE
Android build not working (Kotlin syntax update)

### ISSUE THREAD

**Issue by BrendenFraser** [kineapps/flutter_archive#54] opened 2022-04-11 23:14 UTC
Hi, I believe I've found an issue with flutter_archive on Android. I'm not sure if I'm using an older or newer version of Kotlin from what the plugin was built to use but I believe that's the issue.
```
e: /Users/me/.pub-cache/hosted/pub.dartlang.org/flutter_archive-4.2.0/android/src/main/kotlin/com/kineapps/flutterarchive/FlutterArchivePlugin.kt: (455, 58): Object is not abstract and does not implement abstract member public abstract fun error(p0: String, p1: String?, p2: Any?): Unit defined in io.flutter.plugin.common.MethodChannel.Result
e: /Users/me/.pub-cache/hosted/pub.dartlang.org/flutter_archive-4.2.0/android/src/main/kotlin/com/kineapps/flutterarchive/FlutterArchivePlugin.kt: (472, 17): 'error' overrides nothing
```
The fix is fairly simple, on line 472 in FlutterArchivePlugin.kt, the first ? needs to be removed:
`override fun error(code: String, msg: String?, details: Any?) {`

If I'm using an old version of Kotlin and just need to upgrade, I can close this issue.

**Comment by kinex** [comment] 2022-05-05 16:04
I think this is a duplicate of https://github.com/kineapps/flutter_archive/issues/52 (fixed in master).

**Closed** 2022-05-07 18:54 UTC
